workspace:
  base: /go
  path: src/github.com/drone/envsubst

pipeline:
  build:
    image: golang:1.8
    commands:
      - set -o pipefail
      - go get -t ./...
      - go test -v ./... | tee gotest.out
  gotest:
    image: plugins/gotest:latest
    debug: true
    pull: true
